// Generated by https://quicktype.io

export interface PlacesResponse {
    type:        string;
    features:    Feature[];
    query:       string[];
    attribution: string;
}

export interface Feature {
    type:       string;
    id:         string;
    properties: Properties;
    geometry:   FeatureGeometry;
    bbox:       number[];
    center:     number[];
    place_name: string;
    place_type: string[];
    relevance:  number;
    text:       string;
    context:    Context[];
}

export interface Context {
    id:     string;
    osm_id: string;
    text:   string;
}

export interface FeatureGeometry {
    type:         string;
    coordinates?: Array<Array<number[] | number> | number>;
    geometries?:  GeometryElement[];
}

export interface GeometryElement {
    type:        string;
    coordinates: Array<number[]>;
}

export interface Properties {
    osm_id: string;
}
